services:
  - type: web
    name: secondwear-backend
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/secondwear-0.0.1-SNAPSHOT.jar"